[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "src/functions"  # Opcional, solo si usas Netlify Functions

[dev]
  command = "npm run dev"
  port = 3000

# Configuración específica para Astro
[context.production.environment]
  NODE_VERSION = "18"
  ASTRO_BUILD_DIR = "dist"