[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Opcional, solo si usas Netlify Functions

[dev]
  command = "npm run dev"  # Configuración para desarrollo local
  port = 3000              # Puerto que usa tu aplicación

[context.production.environment]
  NODE_VERSION = "18"      # Usa la misma versión que localmente